/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:388066:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:388066:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:467700:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:467700:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:789014:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:789014:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:498071:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea1:498071:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 366, 279, 80, 30);
  button1.setText("Train!");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  dropList1 = new GDropList(this, 15, 65, 167, 128, 3);
  dropList1.setItems(loadStrings("list_467700"), 1);
  dropList1.addEventHandler(this, "dropList1_click1");
  textfield1 = new GTextField(this, 15, 19, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setPromptText("I am a prompt");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textarea1 = new GTextArea(this, 100, 256, 247, 50, G4P.SCROLLBARS_NONE);
  textarea1.setPromptText("After you \n select your gesture, select this button to being training -> ");
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GDropList dropList1; 
GTextField textfield1; 
GTextArea textarea1; 